const products = [
  {
    id: crypto.randomUUID(),
    title: "Nike Air Force 1 '07 Next Nature",
    category: "Shoes",
    description:
      "The beset shoes in the market I promise you. BUY IT, BUY IT NOW!!!!",
    image: {
      alt: "Nike Air Force 1 '07 Next Nature",
      url: "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/116c99aa-26ac-4fb0-8f1f-257f7b0664fb/W+AIR+FORCE+1+%2707+NEXT+NATURE.png",
    },
    price: 300,
    discount: 0.2,
    instock: 0,
    quantitiy: 0,
  },
  {
    id: crypto.randomUUID(),
    title: "Adidas Ultraboost 21",
    category: "Shoes",
    description: "The ultimate running shoes for comfort and performance.",
    image: {
      alt: "Adidas Ultraboost 21",
      url: "https://assets.adidas.com/images/w_600,f_auto,q_auto/a9efaa3e07424ed2a2eeac3b00e1b1e1_9366/Ultraboost_21_Shoes_White_FY0371_01_standard.jpg",
    },
    price: 180,
    discount: 0.15,
    instock: 10,
    quantitiy: 0,
  },
  {
    id: crypto.randomUUID(),
    title: "Apple iPhone 13",
    category: "Electronics",
    description: "The latest and greatest smartphone from Apple.",
    image: {
      alt: "Apple iPhone 13",
      url: "https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/iphone-13-pro-max-family-hero?wid=940&hei=1112&fmt=png-alpha&.v=1631652955000",
    },
    price: 999,
    discount: 0.1,
    instock: 5,
    quantitiy: 0,
  },
  {
    id: crypto.randomUUID(),
    title: "Samsung Galaxy S21",
    category: "Electronics",
    description: "Experience the power of the new Galaxy S21.",
    image: {
      alt: "Samsung Galaxy S21",
      url: "https://images.samsung.com/is/image/samsung/p6pim/levant/galaxy-s21/gallery/levant-galaxy-s21-s21-plus-5g-g991-sm-g991bzvdmea-368365343?$684_547_PNG$",
    },
    price: 799,
    discount: null,
    instock: 8,
    quantitiy: 0,
  },
  {
    id: crypto.randomUUID(),
    title: "Sony WH-1000XM4",
    category: "Electronics",
    description:
      "Industry-leading noise canceling with Dual Noise Sensor technology.",
    image: {
      alt: "Sony WH-1000XM4",
      url: "https://images.sony.com/is/image/gwtprod/27b9f5c5d6e1bb9ef6d234378021ea4f?fmt=pjpeg&bgcolor=FFFFFF&bgc=FFFFFF&wid=2515&hei=1320",
    },
    price: 350,
    discount: null,
    instock: 15,
    quantitiy: 0,
  },
  {
    id: crypto.randomUUID(),
    title: "Dell XPS 13",
    category: "Electronics",
    description: "Compact, powerful, and designed for professionals on the go.",
    image: {
      alt: "Dell XPS 13",
      url: "https://i.dell.com/sites/imagecontent/products/publishingimages/xps-13-9310-laptop/spi/xps-13-9310-laptop-campaign-hero-504x350-ng.psd",
    },
    price: 1200,
    discount: null,
    instock: 3,
    quantitiy: 0,
  },
  {
    id: crypto.randomUUID(),
    title: "Canon EOS R5",
    category: "Electronics",
    description: "Capture the finest details with the Canon EOS R5.",
    image: {
      alt: "Canon EOS R5",
      url: "https://www.usa.canon.com/internet/portal/us/home/products/details/cameras/eos-r/eos-r5/eos-r5-body",
    },
    price: 3899,
    discount: null,
    instock: 4,
    quantitiy: 0,
  },
  {
    id: crypto.randomUUID(),
    title: "Nike React Infinity Run Flyknit 2",
    category: "Shoes",
    description: "A smooth and stable ride for your everyday runs.",
    image: {
      alt: "Nike React Infinity Run Flyknit 2",
      url: "https://static.nike.com/a/images/t_default/b78c0be3-d0a0-4e67-88c5-c5c8a258bcdb/react-infinity-run-flyknit-2-mens-running-shoe-v5JflD.png",
    },
    price: 160,
    discount: null,
    instock: 12,
    quantitiy: 0,
  },
  {
    id: crypto.randomUUID(),
    title: "Logitech MX Master 3",
    category: "Electronics",
    description: "Advanced wireless mouse for precision and speed.",
    image: {
      alt: "Logitech MX Master 3",
      url: "https://resource.logitech.com/w_800,c_limit,q_auto,f_auto,dpr_1.0/d_transparent.gif/content/dam/logitech/en/products/mice/mx-master-3-mouse/mx-master-3-gallery-graphite-1.png?v=1",
    },
    price: 99,
    discount: null,
    instock: 25,
    quantitiy: 0,
  },
  {
    id: crypto.randomUUID(),
    title: "Razer Blade 15",
    category: "Electronics",
    description: "Powerful gaming laptop with top-notch performance.",
    image: {
      alt: "Razer Blade 15",
      url: "https://assets.razerzone.com/eeimages/products/31600/razer-blade-15-gallery04.jpg",
    },
    price: 2399,
    discount: null,
    instock: 6,
    quantitiy: 0,
  },
  {
    id: crypto.randomUUID(),
    title: "Kindle Paperwhite",
    category: "Electronics",
    description: "Read your favorite books on the go with Kindle Paperwhite.",
    image: {
      alt: "Kindle Paperwhite",
      url: "https://m.media-amazon.com/images/I/61m3deOANGL._AC_SL1000_.jpg",
    },
    price: 129,
    discount: null,
    instock: 20,
    quantitiy: 0,
  },
  {
    id: crypto.randomUUID(),
    title: "GoPro HERO9 Black",
    category: "Electronics",
    description: "Capture your adventures with stunning clarity.",
    image: {
      alt: "GoPro HERO9 Black",
      url: "https://gopro.com/content/dam/gopro/us/en/products/hero9-black/1-hero9-black-carousel-image.png",
    },
    price: 449,
    discount: null,
    instock: 9,
    quantitiy: 0,
  },
  {
    id: crypto.randomUUID(),
    title: "Fitbit Charge 5",
    category: "Electronics",
    description: "Stay on top of your health with advanced fitness tracking.",
    image: {
      alt: "Fitbit Charge 5",
      url: "https://static.adorama.com/images/Large/fb419bybkl.jpg",
    },
    price: 179,
    discount: null,
    instock: 18,
    quantitiy: 0,
  },
  {
    id: crypto.randomUUID(),
    title: "Apple Watch Series 7",
    category: "Electronics",
    description: "Advanced features to keep you connected and healthy.",
    image: {
      alt: "Apple Watch Series 7",
      url: "https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/apple-watch-series-7-digital?wid=5120&hei=2880&fmt=jpeg&qlt=80&.v=1632171022000",
    },
    price: 399,
    discount: null,
    instock: 14,
    quantitiy: 0,
  },
  {
    id: crypto.randomUUID(),
    title: "Microsoft Surface Pro 7",
    category: "Electronics",
    description: "Versatile 2-in-1 laptop with a detachable keyboard.",
    image: {
      alt: "Microsoft Surface Pro 7",
      url: "https://c.s-microsoft.com/en-us/CMSImages/1920_Panel1_Pro7_TypeC_PLQ_MerchPanel.jpg?version=79d9e6f5-3bbf-59da-c336-9acff5154b08",
    },
    price: 749,
    discount: null,
    instock: 7,
    quantitiy: 0,
  },
  {
    id: crypto.randomUUID(),
    title: "Instant Pot Duo 7-in-1",
    category: "Home Appliances",
    description: "Your all-in-one kitchen appliance for easy meals.",
    image: {
      alt: "Instant Pot Duo 7-in-1",
      url: "https://images-na.ssl-images-amazon.com/images/I/81hsD5Th2oL._AC_SL1500_.jpg",
    },
    price: 89,
    discount: null,
    instock: 30,
    quantitiy: 0,
  },
];
